#
# Author : AdNovum Informatik AG
#


server:
  port: 8080
  servlet.session.timeout: 60m
logging:
  path: "/tmp"
  config: /opt/test/app/config/logback-spring.xml
file-location:
  static:
    file:/opt/test/app/static/
name:
  user: "Andrea"